# Site wide configuration

title: "Wei-Hsiang Wang"
description: "STILL TRYING"
logo: red.gif
teaser: 400x250.gif
locale: en_US
#url: "https://mattwang44.github.io/en"
url: "http://localhost:4000"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Wei-Hsiang Wang"
  web: "https://mattwang44.github.io/en"
  #twitter: "mattwang44"
  bio: "Grad. student, Dept. of M.E., NTU, Taiwan"
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  #google:
  #  plus: "+MichaelRoseDesign"
  #  ad-client: "ca-pub-7328585512091257"
  #  ad-slot: 3049671934
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
